name: toy-gan
channels:
  - pytorch
  - plotly
dependencies:
  - python=3
  - pytorch
  - cpuonly
  - pandas
  - matplotlib
  - jupyter
  - torchvision
  - plotly
  - statsmodels
  - psutil
  - plotly-orca
  - pip
  - pip:
    - nbdime
